<!-- src/lib/sims/flight/components/ControlsGUI.svelte -->

<script lang="ts">
  import { onMount } from 'svelte';
  import { writable } from 'svelte/store';
  
  // For the GUI panel
  let gui;
  
  // Physics settings
  const physicsSettings = writable({
    gravity: {
      x: 0,
      y: -8.87, // Venus gravity
      z: 0
    },
    fixedTimeStep: 1/60,
    debugRendering: true
  });
  
  // Player settings
  const playerSettings = writable({
    position: { x: 0, y: 5, z: 0 },
    mass: 10,
    linearDamping: 0.5,
    angularDamping: 0.5,
    restitution: 0.3, // Bounciness
    friction: 0.5
  });
  
  // Atmosphere settings
  const atmosphereSettings = writable({
    fogColor: '#ffebaa',
    fogNear: 50,
    fogFar: 1000,
    hazeOpacity: 0.3,
    hazeRadius: 800
  });
  
  onMount(async () => {
    // Dynamically import lil-gui
    const module = await import('three/examples/jsm/libs/lil-gui.module.min.js');
    const GUI = module.GUI;
    
    // Create GUI
    gui = new GUI({ title: 'Venus Flight Simulator' });
    
    // Physics folder
    const physicsFolder = gui.addFolder('Physics');
    
    physicsFolder.add($physicsSettings.gravity, 'y', -20, 0, 0.01).name('Gravity Y').onChange((value) => {
      physicsSettings.update(s => {
        s.gravity.y = value;
        return s;
      });
      // You would need to update the world gravity here with a callback
    });
    
    physicsFolder.add($physicsSettings, 'fixedTimeStep', 1/120, 1/30, 1/120).name('Time Step');
    physicsFolder.add($physicsSettings, 'debugRendering').name('Debug Rendering');
    
    // Player folder
    const playerFolder = gui.addFolder('Player');
    
    playerFolder.add($playerSettings, 'mass', 1, 100, 1).name('Mass');
    playerFolder.add($playerSettings, 'linearDamping', 0, 1, 0.05).name('Linear Damping');
    playerFolder.add($playerSettings, 'angularDamping', 0, 1, 0.05).name('Angular Damping');
    playerFolder.add($playerSettings, 'restitution', 0, 1, 0.05).name('Bounciness');
    playerFolder.add($playerSettings, 'friction', 0, 1, 0.05).name('Friction');
    
    // Atmosphere folder
    const atmosphereFolder = gui.addFolder('Atmosphere');
    
    atmosphereFolder.addColor($atmosphereSettings, 'fogColor').name('Fog Color');
    atmosphereFolder.add($atmosphereSettings, 'fogNear', 10, 200, 1).name('Fog Near');
    atmosphereFolder.add($atmosphereSettings, 'fogFar', 100, 5000, 10).name('Fog Far');
    atmosphereFolder.add($atmosphereSettings, 'hazeOpacity', 0, 1, 0.05).name('Haze Opacity');
    atmosphereFolder.add($atmosphereSettings, 'hazeRadius', 100, 2000, 50).name('Haze Radius');
    
    return () => {
      // Clean up GUI on component unmount
      gui.destroy();
    };
  });
  
  // Export these stores for other components to subscribe to
  export { physicsSettings, playerSettings, atmosphereSettings };
</script>

<!-- The GUI is generated by lil-gui and doesn't need any HTML markup -->